AutoVentas/Controllers/CuentaController.cs
using AutoVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoVentas.Controllers
{
    public class CuentaController : Controller
    {
        public DB_Carros db = new DB_Carros();

        // GET: Cuenta
        public ActionResult Iniciar()
        {
            if (Session["IDRol"] != null)
            {
                if (Session["IDRol"].Equals(1))
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (Session["IDRol"].Equals(2))
                {
                    return RedirectToAction("Inicio", "Cliente");
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Iniciar(Usuario usuario)
        {
                var user = db.Usuario.FirstOrDefault( u => u.Username == usuario.Username && u.Password == usuario.Password);
                if(user != null)
                {
                    Session["Username"] = user.Username;
                    Session["Nombre"] = user.Nombre;
                    Session["IDUsuario"] = user.IDUsuario;
                    Session["IDRol"] = user.IDRol;
                    if (user.IDRol == 1)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return RedirectToAction("Inicio", "Cliente");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Verifique sus credenciales: Nombre de Usuario o contraseña incorrectos.");
                }
            return View();
        }

        public ActionResult Registrarse()
        {
            if (Session["IDUsuario"] != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Registrarse(Usuario usuario)
        {
            if(ModelState.IsValid)
            {
                Rol rol = db.Rol.FirstOrDefault(r => r.IDRol == 2);
                usuario.Rol = rol;
                db.Usuario.Add(usuario);
                db.SaveChanges();
                ViewBag.mensaje = "El usuario " + usuario.Username + " fue registrado correctamente";
                ModelState.Clear();
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.Remove("IDUsuario");
            Session.Remove("Nombre");
            Session.Remove("Username");
            Session.Remove("IDRol");
            return RedirectToAction("Iniciar");
        }
    }
}

AutoVentas/Views/Cuenta/Iniciar.cshtml
@model AutoVentas.Models.Usuario

@{
    ViewBag.Title = "Iniciar";
}

<h2>Iniciar Sesion</h2>

@using (Html.BeginForm("Iniciar", "Cuenta", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin: 0 auto;">
        <h4>Ingrese sus credenciales por favor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Iniciar Sesion" class="btn btn-success" />
                @Html.ActionLink("Registrarse", "Registrarse", "Cuenta", new { @class = "btn btn-primary btn-flat" })
            </div>
        </div>
    </div>
}

AutoVentas/Views/Cuenta/Registrarse.cshtml
@model AutoVentas.Models.Usuario

@{
    ViewBag.Title = "Registrarse";
}

<h2>Registrarse</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (ViewBag.mensaje != null)
        {
            <div class="alert-success">
                @ViewBag.mensaje
                <br />
            </div>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telegono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telegono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telegono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrarme" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Iniciar", "Cuenta", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}