AutoVentas/Models/TipoCombustible.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AutoVentas.Models
{
    public class TipoCombustible
    {
        [Key]
        public int IDTipoCombustible { get; set; }

        [Display(Name = "Nombre"), Required(ErrorMessage = "El nombre es requerido.")]
        public String Nombre { get; set; }
    }
}

AutoVentas/Controllers/TipoCombustibleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoVentas.Models;

namespace AutoVentas.Controllers
{
    public class TipoCombustibleController : Controller
    {
        private DB_Carros db = new DB_Carros();

        // GET: TipoCombustible
        public ActionResult Index(String filtro)
        {
            if (Session["IDUsuario"] == null)
            {
                return RedirectToAction("Iniciar", "Cuenta");
            }
            else if (!Session["IDRol"].Equals(1))
            {
                return RedirectToAction("Inicio", "Cliente");
            }
            List<TipoCombustible> tipos = new List<TipoCombustible>();
            if (filtro != null)
            {
                tipos = db.TipoCombustible.Where(v => v.Nombre.Contains(filtro)).ToList();
            }
            else
            {
                tipos = db.TipoCombustible.ToList();
            }
            if (filtro == "")
            {
                tipos = db.TipoCombustible.ToList();
            }
            return View(tipos.ToList());
        }

        // GET: TipoCombustible/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["IDUsuario"] == null)
            {
                return RedirectToAction("Iniciar", "Cuenta");
            }
            else if (!Session["IDRol"].Equals(1))
            {
                return RedirectToAction("Inicio", "Cliente");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoCombustible tipoCombustible = db.TipoCombustible.Find(id);
            if (tipoCombustible == null)
            {
                return HttpNotFound();
            }
            return View(tipoCombustible);
        }

        // GET: TipoCombustible/Create
        public ActionResult Create()
        {
            if (Session["IDUsuario"] == null)
            {
                return RedirectToAction("Iniciar", "Cuenta");
            }
            else if (!Session["IDRol"].Equals(1))
            {
                return RedirectToAction("Inicio", "Cliente");
            }
            return View();
        }

        // POST: TipoCombustible/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDTipoCombustible,Nombre")] TipoCombustible tipoCombustible)
        {
            if (ModelState.IsValid)
            {
                db.TipoCombustible.Add(tipoCombustible);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoCombustible);
        }

        // GET: TipoCombustible/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["IDUsuario"] == null)
            {
                return RedirectToAction("Iniciar", "Cuenta");
            }
            else if (!Session["IDRol"].Equals(1))
            {
                return RedirectToAction("Inicio", "Cliente");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoCombustible tipoCombustible = db.TipoCombustible.Find(id);
            if (tipoCombustible == null)
            {
                return HttpNotFound();
            }
            return View(tipoCombustible);
        }

        // POST: TipoCombustible/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDTipoCombustible,Nombre")] TipoCombustible tipoCombustible)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoCombustible).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoCombustible);
        }

        // GET: TipoCombustible/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["IDUsuario"] == null)
            {
                return RedirectToAction("Iniciar", "Cuenta");
            }
            else if (!Session["IDRol"].Equals(1))
            {
                return RedirectToAction("Inicio", "Cliente");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoCombustible tipoCombustible = db.TipoCombustible.Find(id);
            if (tipoCombustible == null)
            {
                return HttpNotFound();
            }
            return View(tipoCombustible);
        }

        // POST: TipoCombustible/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoCombustible tipoCombustible = db.TipoCombustible.Find(id);
            db.TipoCombustible.Remove(tipoCombustible);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoVentas/Views/TipoCombustible/Create.cshtml
@model AutoVentas.Models.TipoCombustible

@{
    ViewBag.Title = "Registrar Tipo de Combustible";
}

<h2>Registrar un Tipo de Combustible</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingrese la informacion que se le solicita</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "TipoCombustible", new { @class = "btn btn-primary btn-flat" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoVentas/Views/TipoCombustible/Delete.cshtml
@model AutoVentas.Models.TipoCombustible

@{
    ViewBag.Title = "Eliminar Tipo de Combustible";
}

<h2>Eliminar Tipo de Combustible</h2>

<h3 class="text-danger">Estas seguro de eliminar este tipo de combustible permanentemente?</h3>
<div>
    <h4>Informacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index", "TipoCombustible", new { @class = "btn btn-primary btn-flat" })
        </div>
    }
</div>

AutoVentas/Views/TipoCombustible/Details.cshtml
@model AutoVentas.Models.TipoCombustible

@{
    ViewBag.Title = "Detalles del Tipo de Combustible";
}

<h2>Detalles del Tipo de Combustible</h2>

<div>
    <h4>Informacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IDTipoCombustible }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Regresar", "Index", "TipoCombustible", new { @class = "btn btn-primary btn-flat" })
</p>

AutoVentas/Views/TipoCombustible/Edit.cshtml
@model AutoVentas.Models.TipoCombustible

@{
    ViewBag.Title = "Editar Tipo de Combustible";
}

<h2>Editar Tipo de Combustible</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Informacion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDTipoCombustible)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "TipoCombustible", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoVentas/Views/TipoCombustible/Index.cshtml
@model IEnumerable<AutoVentas.Models.TipoCombustible>

@{
    ViewBag.Title = "Tipos de Combustible";
}

<h2>Tipos de Combustible Registrados</h2>
<br />
<p>
    @Html.ActionLink("Registrar un Tipo de Combustible", "Create", "TipoCombustible", new { @class = "btn btn-primary" })
</p>
<br />
@using (Html.BeginForm())
{
    <p>
        Buscar:@Html.TextBox("filtro")
        <input type="submit" value="Buscar" />
    </p>
    <br />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.IDTipoCombustible }, new { @class = "btn btn-success" }) |
            @Html.ActionLink("Detalles", "Details", new { id = item.IDTipoCombustible }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Eliminar", "Delete", new { id = item.IDTipoCombustible }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>